// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';

clientsClaim();

// Add cache versioning to force invalidation on updates
const CACHE_VERSION = 'v1.0.1755055115531'; // This will be updated with each deployment
const CACHE_NAMES = {
  static: `static-resources-${CACHE_VERSION}`,
  images: `images-${CACHE_VERSION}`,
  api: `api-cache-${CACHE_VERSION}`,
  appShell: `app-shell-${CACHE_VERSION}`,
  dynamic: `dynamic-cache-${CACHE_VERSION}`,
};

// Clean up old caches on service worker activation
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((cacheNames) => {
        return Promise.all(
          cacheNames.map((cacheName) => {
            // Delete caches that don't match our current version
            if (!Object.values(CACHE_NAMES).includes(cacheName)) {
              console.log('Deleting old cache:', cacheName);
              return caches.delete(cacheName);
            }
          })
        );
      })
      .then(() => {
        // Force clients to reload to ensure they get the latest version
        return self.clients.claim();
      })
  );
});

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Add a more aggressive cache strategy for the main HTML file
// This ensures the app shell is always fresh on navigation
registerRoute(
  ({ url }) => url.pathname === '/' || url.pathname === '/index.html',
  new NetworkFirst({
    cacheName: CACHE_NAMES.appShell,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 1,
        maxAgeSeconds: 60 * 5, // 5 minutes - very short cache for main HTML
      }),
    ],
  })
);

// Cache images with a stale-while-revalidate strategy
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith('.png'),
  new StaleWhileRevalidate({
    cacheName: CACHE_NAMES.images,
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  })
);

// Cache CSS and JS files with a network-first strategy for better updates
registerRoute(
  ({ request }) =>
    request.destination === 'style' || request.destination === 'script',
  new NetworkFirst({
    cacheName: CACHE_NAMES.static,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours - shorter cache for better updates
      }),
    ],
  })
);

// Cache API requests with a network-first strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: CACHE_NAMES.api,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Handle offline scenarios for requests not handled by Workbox
self.addEventListener('fetch', (event) => {
  // Only handle requests that haven't been handled by Workbox routes
  if (event.request.method !== 'GET') {
    return;
  }

  // Skip if this is a navigation request (handled by Workbox)
  if (event.request.mode === 'navigate') {
    return;
  }

  // Skip if this is a request that should be handled by Workbox routes
  const url = new URL(event.request.url);
  if (
    url.pathname.endsWith('.png') ||
    event.request.destination === 'style' ||
    event.request.destination === 'script' ||
    url.pathname.startsWith('/api/')
  ) {
    return;
  }

  // For other requests, try network first, then cache
  event.respondWith(
    fetch(event.request)
      .then((response) => {
        // Only cache successful responses
        if (!response || response.status !== 200 || response.type !== 'basic') {
          return response;
        }

        // Clone the response before returning it
        const responseClone = response.clone();

        // Cache the response for future use
        caches.open(CACHE_NAMES.dynamic).then((cache) => {
          cache.put(event.request, responseClone);
        });

        return response;
      })
      .catch(() => {
        // If network fails, try to get from cache
        return caches.match(event.request);
      })
  );
});
