import { describe, it, expect } from 'vitest';
import {
  rotateNames,
  rotateRound,
  rotateDealerId,
  rotateGameState,
  SEAT_ORDER,
} from './perspective';
import type { Names, Round, AppState } from '../../types';

const names: Names = {
  t1p1Name: 'You',
  t2p1Name: 'Left',
  t1p2Name: 'Partner',
  t2p2Name: 'Right',
  team1Name: 'Team 1',
  team2Name: 'Team 2',
};

describe('rotateNames (viewer perspective)', () => {
  it('leaves the board unchanged for the leader seat (t1p1)', () => {
    expect(rotateNames(names, 't1p1')).toEqual(names);
  });

  it('rotates 180° when viewing from the partner seat (t1p2)', () => {
    expect(rotateNames(names, 't1p2')).toEqual({
      t1p1Name: 'Partner',
      t2p1Name: 'Right',
      t1p2Name: 'You',
      t2p2Name: 'Left',
      team1Name: 'Team 1',
      team2Name: 'Team 2',
    });
  });

  // The exact bug reported: dad is to my left (t2p1). Viewing from dad's seat,
  // I should appear at his RIGHT (t2p2) — not his left.
  it('places "You" at the RIGHT of the left-seat (t2p1) viewer', () => {
    const result = rotateNames(names, 't2p1');
    // dad (Left) is now the "you" position
    expect(result.t1p1Name).toBe('Left');
    // I (You) am now at dad's right
    expect(result.t2p2Name).toBe('You');
    // my partner is at dad's left
    expect(result.t2p1Name).toBe('Partner');
    // dad's right-seat teammate is opposite him
    expect(result.t1p2Name).toBe('Right');
    // teams swap so the viewer's team is in the left column
    expect(result.team1Name).toBe('Team 2');
    expect(result.team2Name).toBe('Team 1');
  });

  it('places "You" at the LEFT of the right-seat (t2p2) viewer', () => {
    const result = rotateNames(names, 't2p2');
    expect(result.t1p1Name).toBe('Right');
    expect(result.t2p1Name).toBe('You');
    expect(result.t2p2Name).toBe('Partner');
    expect(result.t1p2Name).toBe('Left');
    expect(result.team1Name).toBe('Team 2');
    expect(result.team2Name).toBe('Team 1');
  });

  it('covers all four seats in the fixed table order', () => {
    expect(SEAT_ORDER).toEqual(['t1p1', 't2p1', 't1p2', 't2p2']);
  });
});

describe('rotateRound (viewer perspective)', () => {
  const round: Round = {
    team1BidsAndActuals: {
      p1Bid: '1',
      p2Bid: '2',
      p1Actual: '1',
      p2Actual: '2',
    },
    team2BidsAndActuals: {
      p1Bid: '3',
      p2Bid: '4',
      p1Actual: '3',
      p2Actual: '4',
    },
  } as Round;

  it('leaves the round unchanged for the leader seat', () => {
    expect(rotateRound(round, 't1p1')).toEqual(round);
  });

  it('rotates bids/actuals so each player keeps their own numbers from t2p1', () => {
    // Seat → (team, player): t1p1=team1.p1, t2p1=team2.p1, t1p2=team1.p2, t2p2=team2.p2
    const result = rotateRound(round, 't2p1');
    expect(result.team1BidsAndActuals.p1Bid).toBe('3'); // dad (team2.p1) → you slot
    expect(result.team1BidsAndActuals.p2Bid).toBe('4'); // right (team2.p2) → partner slot
    expect(result.team2BidsAndActuals.p1Bid).toBe('2'); // partner (team1.p2) → left slot
    expect(result.team2BidsAndActuals.p2Bid).toBe('1'); // you (team1.p1) → right slot
  });

  it('rotates autoGeneratedActuals so the asterisk follows the player from t2p1', () => {
    const roundWithAuto: Round = {
      ...round,
      autoGeneratedActuals: {
        team1P1: true, // only the leader's (t1p1) actual was auto-generated
        team1P2: false,
        team2P1: false,
        team2P2: false,
      },
    };
    const result = rotateRound(roundWithAuto, 't2p1');
    // t1p1's auto flag moves to the right slot (t2p2); every other seat is false.
    expect(result.autoGeneratedActuals).toEqual({
      team1P1: false, // you slot (now t2p1's actual)
      team1P2: false, // partner slot (now t2p2's actual)
      team2P1: false, // left slot (now t1p2's actual)
      team2P2: true, // right slot (now t1p1's actual)
    });
  });

  it('leaves autoGeneratedActuals unchanged for the leader seat', () => {
    const roundWithAuto: Round = {
      ...round,
      autoGeneratedActuals: {
        team1P1: true,
        team1P2: false,
        team2P1: false,
        team2P2: true,
      },
    };
    expect(rotateRound(roundWithAuto, 't1p1').autoGeneratedActuals).toEqual(
      roundWithAuto.autoGeneratedActuals,
    );
  });
});

describe('rotateDealerId (viewer perspective)', () => {
  it('leaves the dealer id unchanged for the leader seat (t1p1)', () => {
    expect(rotateDealerId('team1BidsAndActuals.p1Bid', 't1p1')).toBe(
      'team1BidsAndActuals.p1Bid',
    );
  });

  it('rotates the t1p1 dealer to the right slot for a t2p1 viewer', () => {
    expect(rotateDealerId('team1BidsAndActuals.p1Bid', 't2p1')).toBe(
      'team2BidsAndActuals.p2Bid',
    );
  });

  it('rotates the t1p1 dealer to the partner slot for a t1p2 viewer', () => {
    expect(rotateDealerId('team1BidsAndActuals.p1Bid', 't1p2')).toBe(
      'team1BidsAndActuals.p2Bid',
    );
  });

  it('rotates the t1p1 dealer to the left slot for a t2p2 viewer', () => {
    expect(rotateDealerId('team1BidsAndActuals.p1Bid', 't2p2')).toBe(
      'team2BidsAndActuals.p1Bid',
    );
  });

  it('places a t2p1 dealer in the "you" slot when the viewer is t2p1', () => {
    expect(rotateDealerId('team2BidsAndActuals.p1Bid', 't2p1')).toBe(
      'team1BidsAndActuals.p1Bid',
    );
  });

  it('returns an unknown dealer id unchanged', () => {
    expect(rotateDealerId('not-a-real-id', 't2p1')).toBe('not-a-real-id');
  });
});

describe('rotateGameState (seed the game on viewer leave)', () => {
  const state: AppState = {
    currentRound: {
      team1BidsAndActuals: { p1Bid: '2', p2Bid: '4', p1Actual: '', p2Actual: '' },
      team2BidsAndActuals: { p1Bid: '6', p2Bid: '8', p1Actual: '', p2Actual: '' },
      dealerOverride: 'team2BidsAndActuals.p1Bid',
      autoGeneratedActuals: {
        team1P1: false,
        team1P2: false,
        team2P1: false,
        team2P2: false,
      },
    },
    roundHistory: [
      {
        team1BidsAndActuals: {
          p1Bid: '5',
          p2Bid: '6',
          p1Actual: '5',
          p2Actual: '6',
        },
        team2BidsAndActuals: {
          p1Bid: '7',
          p2Bid: '8',
          p1Actual: '7',
          p2Actual: '8',
        },
        dealerOverride: null,
      },
    ],
    firstDealerOrder: [
      'team1BidsAndActuals.p1Bid',
      'team2BidsAndActuals.p1Bid',
      'team1BidsAndActuals.p2Bid',
      'team2BidsAndActuals.p2Bid',
    ],
    isFirstGameAmongTeammates: true,
    names,
    nilScoringRule: 'takesBags',
    scoreLimit: null,
    winAcknowledged: null,
  };

  it('returns the same state for the leader seat (t1p1)', () => {
    expect(rotateGameState(state, 't1p1')).toBe(state);
  });

  it('rotates names, rounds, and dealer order together for a t2p1 viewer', () => {
    const result = rotateGameState(state, 't2p1');

    expect(result.names.t1p1Name).toBe('Left');
    expect(result.names.team1Name).toBe('Team 2');

    expect(result.currentRound.team1BidsAndActuals.p1Bid).toBe('6');
    expect(result.currentRound.dealerOverride).toBe('team1BidsAndActuals.p1Bid');

    expect(result.roundHistory[0].team1BidsAndActuals.p1Bid).toBe('7');

    expect(result.firstDealerOrder).toEqual([
      'team2BidsAndActuals.p2Bid',
      'team1BidsAndActuals.p1Bid',
      'team2BidsAndActuals.p1Bid',
      'team1BidsAndActuals.p2Bid',
    ]);
  });

  it('keeps game-level fields verbatim', () => {
    const result = rotateGameState(state, 't2p1');
    expect(result.isFirstGameAmongTeammates).toBe(true);
    expect(result.nilScoringRule).toBe('takesBags');
  });
});
