import {
  defaultLocalStorage,
  setLocalStorage,
  getLocalStorage,
} from './helperFunctions';
import { initialFirstDealerOrder } from './constants';
import type { AppState, AppAction, Round } from '../../types';

export const initialState = {
  currentRound: defaultLocalStorage('currentRound', {
    team1BidsAndActuals: {
      p1Bid: '',
      p2Bid: '',
      p1Actual: '',
      p2Actual: '',
    },
    team2BidsAndActuals: {
      p1Bid: '',
      p2Bid: '',
      p1Actual: '',
      p2Actual: '',
    },
    dealerOverride: null, // Add dealer override for current round
    autoGeneratedActuals: {
      team1P1: false,
      team1P2: false,
      team2P1: false,
      team2P2: false,
    },
  }),
  roundHistory: defaultLocalStorage('roundHistory', []),
  firstDealerOrder: defaultLocalStorage(
    'firstDealerOrder',
    initialFirstDealerOrder
  ),
  isFirstGameAmongTeammates: defaultLocalStorage(
    'isFirstGameAmongTeammates',
    true
  ),
};

const rootReducer = (state: AppState, action: AppAction): AppState => {

  switch (action.type) {
    case 'SET_CURRENT_ROUND':
      try {
        setLocalStorage('currentRound', { ...action.payload.currentRound });
        const round = getLocalStorage<Round>('currentRound');
        return {
          ...state,
          currentRound: round ? round : state.currentRound,
        };
      } catch (err) {
        console.error(err);
        return state;
      }
    case 'RESET_CURRENT_ROUND':
      try {
        setLocalStorage('currentRound', {
          team1BidsAndActuals: {
            p1Bid: '',
            p2Bid: '',
            p1Actual: '',
            p2Actual: '',
          },
          team2BidsAndActuals: {
            p1Bid: '',
            p2Bid: '',
            p1Actual: '',
            p2Actual: '',
          },
          dealerOverride: null, // Clear dealer override for new round
          autoGeneratedActuals: {
            team1P1: false,
            team1P2: false,
            team2P1: false,
            team2P2: false,
          },
        });
        const round = getLocalStorage<Round>('currentRound');
        return {
          ...state,
          currentRound: round ? round : state.currentRound,
        };
      } catch (err) {
        console.error(err);
        return state;
      }
    case 'RESET_ROUND_HISTORY':
      return {
        ...state,
        roundHistory: [],
      };
    case 'SET_ROUND_HISTORY':
      try {
        setLocalStorage('roundHistory', [...action.payload.roundHistory]);
        const history = getLocalStorage<Round[]>('roundHistory');
        return {
          ...state,
          roundHistory: history ? history : state.roundHistory,
        };
      } catch (err) {
        console.error(err);
        return state;
      }
    case 'SET_FIRST_DEALER_ORDER':
      try {
        setLocalStorage('firstDealerOrder', [...action.payload.firstDealerOrder]);
        const order = getLocalStorage<string[]>('firstDealerOrder');
        return {
          ...state,
          firstDealerOrder: order ? order : state.firstDealerOrder,
        };
      } catch (err) {
        console.error(err);
        return state;
      }
    case 'SET_DEALER_OVERRIDE':
      try {
        const updatedCurrentRound = {
          ...state.currentRound,
          dealerOverride: action.payload.dealerOverride,
        };

        setLocalStorage('currentRound', updatedCurrentRound);
        const storedRound = getLocalStorage<Round>('currentRound');

        return {
          ...state,
          currentRound: storedRound ? storedRound : state.currentRound,
        };
      } catch (err) {
        console.error('Error in SET_DEALER_OVERRIDE:', err);
        return state;
      }
    default:
      console.log('default called');
      return state;
  }
};

export default rootReducer;
