import {
  createContext,
  useReducer,
  ReactNode,
  useCallback,
  useMemo,
  useState,
  useEffect,
  useRef,
} from 'react';
import rootReducer, { getInitialState } from './rootReducer';
import { updateInput } from '../helpers/utils/helperFunctions';
import {
  isRealtimeEnabled,
  createSession,
  writeSessionState,
  subscribeSession,
} from '../firebase/realtime';
import { rotateNames, rotateRound, rotateGameState } from '../helpers/utils/perspective';
import {
  persistViewerSession,
  clearPersistedViewerSession,
  persistViewerSeat,
  getPersistedViewerSeat,
  hasOwnLocalGame,
} from '../helpers/utils/viewerSession';
import { setFeatureFlag, FEATURE_FLAGS } from '../helpers/utils/featureFlags';
import type {
  GlobalContextValue,
  UpdateInputArgs,
  Round,
  InputValue,
  AppState,
  Names,
  NilSetting,
  Seat,
  SessionRole,
  WinAcknowledgement,
} from '../types';

export const GlobalContext = createContext<GlobalContextValue>(
  {} as GlobalContextValue,
);

const isTeamTotalUpdate = (fieldToUpdate: string) => {
  return fieldToUpdate.includes('team') && fieldToUpdate.includes('Total');
};

const isActualUpdate = (fieldToUpdate: string) => {
  return fieldToUpdate.includes('Actual');
};

const buildTeamTotalRound = ({
  input,
  fieldToUpdate,
  currentRound,
}: UpdateInputArgs): Round => {
  const teamNumber = fieldToUpdate.includes('team1') ? 1 : 2;
  const teamField =
    teamNumber === 1 ? 'team1BidsAndActuals' : 'team2BidsAndActuals';

  const numInput = parseInt(input as string, 10);
  const individualValue = Math.floor(numInput / 2);
  const remainder = numInput % 2;
  const p1Value = individualValue + remainder;

  const autoGeneratedKey1 = teamNumber === 1 ? 'team1P1' : 'team2P1';
  const autoGeneratedKey2 = teamNumber === 1 ? 'team1P2' : 'team2P2';

  return {
    ...currentRound,
    [teamField]: {
      ...currentRound[teamField],
      p1Actual: String(p1Value) as InputValue,
      p2Actual: String(individualValue) as InputValue,
    },
    autoGeneratedActuals: {
      ...currentRound.autoGeneratedActuals,
      [autoGeneratedKey1]: true,
      [autoGeneratedKey2]: true,
    } as Round['autoGeneratedActuals'],
  };
};

const buildActualRound = (args: UpdateInputArgs): Round => {
  const { fieldToUpdate } = args;
  const teamNumber = fieldToUpdate.includes('team1') ? 1 : 2;
  const playerNumber = fieldToUpdate.includes('p1Actual') ? 'P1' : 'P2';
  const autoGeneratedKey = `team${teamNumber}${playerNumber}`;

  const updatedRound = updateInput(args);

  return {
    ...updatedRound,
    autoGeneratedActuals: {
      ...updatedRound.autoGeneratedActuals,
      [autoGeneratedKey]: false,
    } as Round['autoGeneratedActuals'],
  };
};

export const StateProvider = ({ children }: { children: ReactNode }) => {
  const [state, dispatch] = useReducer(
    rootReducer,
    undefined as unknown as AppState,
    getInitialState,
  );

  // ── Realtime session state ─────────────────────────────────────────────
  const [role, setRole] = useState<SessionRole>('local');
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [seat, setSeat] = useState<Seat>('t1p1');
  const [isViewerSynced, setIsViewerSynced] = useState(false);
  const seatRef = useRef(seat);
  const sessionIdRef = useRef(sessionId);
  const uiModeAppliedRef = useRef(false);

  // Keep refs in sync with state — avoids direct ref mutation during render
  useEffect(() => {
    seatRef.current = seat;
  }, [seat]);
  useEffect(() => {
    sessionIdRef.current = sessionId;
  }, [sessionId]);

  const startLeaderSession = useCallback(async () => {
    const existing = sessionIdRef.current;
    if (existing) {
      setRole('leader');
      return;
    }
    if (!isRealtimeEnabled()) {
      console.warn('Firebase is not configured yet.');
      return;
    }
    const id = await createSession(state);
    setSessionId(id);
    setRole('leader');
  }, [state]);

  const joinSession = useCallback((id: string) => {
    setSessionId(id);
    setRole('viewer');
    persistViewerSession(id);
    const persistedSeat = getPersistedViewerSeat();
    if (persistedSeat) setSeat(persistedSeat as Seat);
  }, []);

  const endSession = useCallback(() => {
    setRole('local');
    setSessionId(null);
    setIsViewerSynced(false);
    uiModeAppliedRef.current = false;
    clearPersistedViewerSession();
    if (hasOwnLocalGame()) {
      // This device has its own game: restore it, undoing the hydrated leader
      // board.
      dispatch({ type: 'RESTORE_LOCAL' });
    } else {
      // Fresh device: seed the name form AND the board with the FULL watched
      // game, rotated so the viewer's chosen seat lands in the "you" (t1p1)
      // slot. Leaving must not blank the game — the leader's rounds carry over
      // so "Continue" resumes where they left off. In-memory only, so
      // `hasOwnLocalGame()` stays false and the leave flow lands on the form.
      dispatch({
        type: 'SEED_GAME_FROM_VIEW',
        payload: rotateGameState(state, seat),
      });
    }
    // The chosen seat is deliberately NOT cleared: it's a stable per-device
    // preference ("where am I sitting?"), so leaving a session and rejoining
    // (Undo, or re-opening the link) must not re-prompt for the seat.
  }, [state, seat]);

  // Seat selection is persisted so a viewer who navigates away and back keeps
  // their chosen perspective instead of being re-prompted.
  const setSeatAndPersist = useCallback((nextSeat: Seat) => {
    setSeat(nextSeat);
    persistViewerSeat(nextSeat);
  }, []);

  // Viewer perspective: rotate the four seats so the viewer's own seat is in
  // the "you" position. This preserves left/right correctly (a team mirror
  // would invert them). Team 1 / leader seats simply aren't rotated.
  const isViewer = role === 'viewer';

  const displayNames = useMemo(
    () => (isViewer ? rotateNames(state.names, seat) : state.names),
    [isViewer, state.names, seat],
  );

  const viewCurrentRound = useMemo(
    () => (isViewer ? rotateRound(state.currentRound, seat) : state.currentRound),
    [isViewer, state.currentRound, seat],
  );

  const viewRoundHistory = useMemo(
    () =>
      isViewer
        ? state.roundHistory.map((round) => rotateRound(round, seat))
        : state.roundHistory,
    [isViewer, state.roundHistory, seat],
  );

  // Leader: push state to the session on every change (debounced).
  useEffect(() => {
    if (role !== 'leader' || !sessionId) return;
    const timer = window.setTimeout(() => {
      writeSessionState(sessionId, state).catch((err) =>
        console.error('Failed to write session state:', err),
      );
    }, 200);
    return () => window.clearTimeout(timer);
  }, [state, role, sessionId]);

  // Viewer: subscribe to the session and hydrate as the leader writes.
  useEffect(() => {
    if (role !== 'viewer' || !sessionId) return;
    const unsubscribe = subscribeSession(
      sessionId,
      (incoming) => {
        dispatch({ type: 'HYDRATE', payload: incoming });
        setIsViewerSynced(true);
      },
      (err) => console.error('Session subscribe error:', err),
      (uiMode) => {
        // Apply the leader's UI mode as the default on first sync only. The
        // viewer can subsequently toggle their own layout via Settings.
        if (uiModeAppliedRef.current) return;
        uiModeAppliedRef.current = true;
        setFeatureFlag(FEATURE_FLAGS.TABLE_ROUND_UI, uiMode);
      },
    );
    return unsubscribe;
  }, [role, sessionId]);

  const setCurrentRound = useCallback((args: UpdateInputArgs) => {
    if (isTeamTotalUpdate(args.fieldToUpdate)) {
      dispatch({
        type: 'SET_CURRENT_ROUND',
        payload: { currentRound: buildTeamTotalRound(args) },
      });
    } else if (isActualUpdate(args.fieldToUpdate)) {
      dispatch({
        type: 'SET_CURRENT_ROUND',
        payload: { currentRound: buildActualRound(args) },
      });
    } else {
      dispatch({
        type: 'SET_CURRENT_ROUND',
        payload: { currentRound: updateInput(args) },
      });
    }
  }, []);

  const resetCurrentRound = useCallback(() => {
    dispatch({
      type: 'RESET_CURRENT_ROUND',
    });
  }, []);

  const setRoundHistory = useCallback((newRoundHistory: Round[]) => {
    const clonedNewRoundHistory = [...newRoundHistory];
    dispatch({
      type: 'SET_ROUND_HISTORY',
      payload: {
        roundHistory: clonedNewRoundHistory,
      },
    });
  }, []);

  const setFirstDealerOrder = useCallback((newFirstDealerOrder: string[]) => {
    const clonedNewFirstDealerOrder = [...newFirstDealerOrder];
    dispatch({
      type: 'SET_FIRST_DEALER_ORDER',
      payload: {
        firstDealerOrder: clonedNewFirstDealerOrder,
      },
    });
  }, []);

  const setDealerOverride = useCallback((dealerOverride: string | null) => {
    dispatch({
      type: 'SET_DEALER_OVERRIDE',
      payload: {
        dealerOverride,
      },
    });
  }, []);

  const resetRoundHistory = useCallback(() => {
    dispatch({
      type: 'RESET_ROUND_HISTORY',
    });
  }, []);

  const setNames = useCallback(
    (names: Names | ((val: Names) => Names)) => {
      const valueToStore =
        names instanceof Function ? names(state.names) : names;
      dispatch({
        type: 'SET_NAMES',
        payload: { names: valueToStore },
      });
    },
    [state.names],
  );

  const setNilScoringRule = useCallback((rule: NilSetting) => {
    dispatch({
      type: 'SET_NIL_SCORING_RULE',
      payload: { nilScoringRule: rule },
    });
  }, []);

  const setScoreLimit = useCallback((limit: number | null) => {
    dispatch({
      type: 'SET_SCORE_LIMIT',
      payload: { scoreLimit: limit },
    });
  }, []);

  const setWinAcknowledged = useCallback(
    (winAcknowledged: WinAcknowledgement | null) => {
      dispatch({
        type: 'SET_WIN_ACKNOWLEDGED',
        payload: { winAcknowledged },
      });
    },
    [],
  );

  const startNewGame = useCallback((limit: number | null) => {
    dispatch({
      type: 'START_NEW_GAME',
      payload: { scoreLimit: limit },
    });
  }, []);

  const globalStore = useMemo(
    () => ({
      setCurrentRound,
      setRoundHistory,
      resetRoundHistory,
      resetCurrentRound,
      setFirstDealerOrder,
      setDealerOverride,
      setNames,
      setNilScoringRule,
      setScoreLimit,
      startNewGame,
      setWinAcknowledged,
      firstDealerOrder: state.firstDealerOrder,
      currentRound: state.currentRound,
      roundHistory: state.roundHistory,
      isFirstGameAmongTeammates: state.isFirstGameAmongTeammates,
      names: state.names,
      nilScoringRule: state.nilScoringRule,
      scoreLimit: state.scoreLimit,
      winAcknowledged: state.winAcknowledged,
      displayNames,
      viewCurrentRound,
      viewRoundHistory,
      role,
      sessionId,
      seat,
      isViewerSynced,
      startLeaderSession,
      joinSession,
      setSeat: setSeatAndPersist,
      endSession,
    }),
    [
      setCurrentRound,
      setRoundHistory,
      resetRoundHistory,
      resetCurrentRound,
      setFirstDealerOrder,
      setDealerOverride,
      setNames,
      setNilScoringRule,
      setScoreLimit,
      startNewGame,
      setWinAcknowledged,
      state.firstDealerOrder,
      state.currentRound,
      state.roundHistory,
      state.isFirstGameAmongTeammates,
      state.names,
      state.nilScoringRule,
      state.scoreLimit,
      state.winAcknowledged,
      displayNames,
      viewCurrentRound,
      viewRoundHistory,
      role,
      sessionId,
      seat,
      isViewerSynced,
      startLeaderSession,
      joinSession,
      setSeatAndPersist,
      endSession,
    ],
  );

  return (
    <GlobalContext.Provider value={globalStore}>
      {children}
    </GlobalContext.Provider>
  );
};
