import { useContext, useState } from 'react';
import { Box, Flex, Text } from '../ui';
import {
  isNotDefaultValue,
  addInputs,
} from '../../helpers/math/spadesMath';
import { useIndependentTeamScoring } from '../../helpers/utils/hooks';
import { GlobalContext } from '../../helpers/context/GlobalContext';
import { InputModal } from '../modals';
import DealerTag from '../ui/DealerTag';
import { ErrorModal } from '../modals';
import Unclaimed from './Unclaimed';
import { useValidateActuals, useGameScores } from '../../helpers/utils/hooks';
import { getActualsErrorText } from '../../helpers/utils/helperFunctions';

const TablePlayerInput = ({
  playerInput,
  type,
  playerName,
  isCurrent,
  roundHistory,
  index,
  dealerId,
  teamClassName,
  currentRound,
  fieldToUpdate,
  onOpenModal,
  bidDisplay, // Pass bid specific string if needed
  showBid,    // Pass boolean to show bid
  bidField,   // Pass bid field for editing
}) => {
  const isAutoGenerated = () => {
    if (type !== 'Actual') return false;
    if (!currentRound || !currentRound.autoGeneratedActuals) return false;

    const isTeam1 = fieldToUpdate.includes('team1');
    const isP1 = fieldToUpdate.includes('p1Actual');
    const key = isTeam1
      ? isP1
        ? 'team1P1'
        : 'team1P2'
      : isP1
      ? 'team2P1'
      : 'team2P2';

    return currentRound.autoGeneratedActuals[key] === true;
  };

  const displayValue =
    playerInput === '' ? '' : `${playerInput}${isAutoGenerated() ? '*' : ''}`;

  return (
    <Flex
      direction="column"
      align="center"
      justify="center"
      position="relative"
    >
      <Flex
        direction="column"
        align="center"
        justify="center"
        cursor="pointer"
        onClick={() => onOpenModal({ fieldToUpdate, type, playerName })}
        p={2}
        borderRadius="md"
        _hover={{ bg: 'whiteAlpha.100' }}
        _focus={{ outline: 'none' }}
        title={`Edit ${type}`}
        data-cy={displayValue ? 'playerInput' : (type === 'Bid' ? 'bidButton' : 'actualButton')}
        data-testid={displayValue ? 'playerInput' : (type === 'Bid' ? 'bidButton' : 'actualButton')}
      >
        <Flex align="center" mb={1}>
          <Text fontWeight="bold" fontSize="md" mr={1}>
            {playerName}
          </Text>
          {type === 'Bid' && (
            <DealerTag
              id={dealerId}
              index={index}
              isCurrent={isCurrent}
              roundHistory={roundHistory}
            />
          )}
        </Flex>
        
        <Flex
          align="center"
          justify="center"
          border="1px solid"
          borderColor={teamClassName === 'team1' ? 'team1' : 'team2'}
          borderRadius="full"
          w="80px"
          h="40px"
          bg={displayValue ? (teamClassName === 'team1' ? 'team1' : 'team2') : 'gray.900'} 
        >
          <Text
            fontSize="lg"
            fontWeight="bold"
            color={displayValue ? 'white' : (teamClassName === 'team1' ? 'team1' : 'team2')}
            textAlign="center"
          >
            {displayValue || type}
          </Text>
        </Flex>
      </Flex>
      
      {/* Bid Display Pill - Only shown in Actuals phase */}
      {showBid && (
        <Flex
            position="absolute"
            top="100%"
            left="50%"
            transform="translateX(-50%)"
            mt={1}
            bg="gray.800"
            border="1px solid"
            borderColor="gray.600"
            borderRadius="full"
            px={2}
            py={0.5}
            align="center"
            justify="center"
            zIndex={20}
            minW="50px"
            cursor="pointer"
            _hover={{ bg: 'gray.700' }}
            onClick={(e) => {
                e.stopPropagation();
                onOpenModal({ fieldToUpdate: bidField, type: 'Bid', playerName });
            }}
        >
            <Text fontSize="xs" color="gray.300" fontWeight="bold">Bid {bidDisplay}</Text>
        </Flex>
      )}
    </Flex>
  );
};

const TeamTotalDisplay = ({
  teamName,
  bidTotal,
  actualTotal,
  isActualsPhase,
  teamClassName,
  onOpenModal,
  isAuto,
}) => {
  return (
    <Flex direction="column" align="center" p={2} bg="blackAlpha.400" borderRadius="md">
        <Text fontWeight="bold" fontSize="sm" color={teamClassName === 'team1' ? 'team1' : 'team2'} mb={1}>
            {teamName}
        </Text>
        <Text fontSize="xs" color="gray.300">Bid: {bidTotal}</Text>
        
        {isActualsPhase ? (
             <Flex 
                align="center" 
                mt={1} 
                cursor="pointer" 
                onClick={onOpenModal}
                _hover={{ opacity: 0.8 }}
                direction="column"
             >
                <Text fontSize="xs" fontWeight="bold">Actual: {actualTotal}</Text>
                {isAuto && (
                    <Text fontSize="xs" color="gray.500" mt="-2px" lineHeight="1">*</Text>
                )}
             </Flex>
        ) : (
            <Text fontSize="xs" color="gray.500">Actual: -</Text>
        )}
    </Flex>
  );
};

const GameScoreDisplay = ({ teamName, score, bags, teamClassName }) => (
    <Flex direction="column" align="center" p={2} borderRadius="md">
        <Text fontWeight="bold" fontSize="md" color={teamClassName === 'team1' ? 'team1' : 'team2'} mb={1}>
            {teamName}
        </Text>
        <Text fontSize="2xl" fontWeight="bold" lineHeight="1">{score}</Text>
        <Text fontSize="xs" color="gray.400">{bags} bags</Text>
    </Flex>
);

function TableRound({ roundHistory, isCurrent = false, roundIndex }) {
  const names = JSON.parse(localStorage.getItem('names'));
  const { team1Name, team2Name, t1p1Name, t1p2Name, t2p1Name, t2p2Name } = names;
  const { currentRound, resetCurrentRound, setRoundHistory } = useContext(GlobalContext);

  // Hook for independent scoring logic
  useIndependentTeamScoring(
    currentRound,
    resetCurrentRound,
    isNotDefaultValue,
    setRoundHistory,
    roundHistory
  );

  const { team1Score, team2Score } = useGameScores();

  const { team1BidsAndActuals, team2BidsAndActuals } = currentRound || {
    team1BidsAndActuals: {},
    team2BidsAndActuals: {},
  };

  const allBidsEntered =
    isNotDefaultValue(team1BidsAndActuals.p1Bid) &&
    isNotDefaultValue(team1BidsAndActuals.p2Bid) &&
    isNotDefaultValue(team2BidsAndActuals.p1Bid) &&
    isNotDefaultValue(team2BidsAndActuals.p2Bid);

  // Calculate Unclaimed Bids
  const team1TotalBid = addInputs(
    team1BidsAndActuals.p1Bid,
    team1BidsAndActuals.p2Bid
  );
  const team2TotalBid = addInputs(
    team2BidsAndActuals.p1Bid,
    team2BidsAndActuals.p2Bid
  );
  const totalBids = team1TotalBid + team2TotalBid;
  const unclaimed = 13 - totalBids;

  // Validation Check for Actuals
  const [isValid, setIsValid] = useState(true);
  
  const p1Actual = team1BidsAndActuals.p1Actual || '';
  const p2Actual = team1BidsAndActuals.p2Actual || '';
  const p3Actual = team2BidsAndActuals.p1Actual || ''; 
  const p4Actual = team2BidsAndActuals.p2Actual || ''; 

  const allActualsSubmitted = [p1Actual, p2Actual, p3Actual, p4Actual].every(val => isNotDefaultValue(val));
  const totalActuals = addInputs(p1Actual, p2Actual, p3Actual, p4Actual);
  
  useValidateActuals(allActualsSubmitted, totalActuals, setIsValid);

  // Modal State Logic Hoisted
  const [modalState, setModalState] = useState({
    isOpen: false,
    fieldToUpdate: '',
    playerName: '',
    type: 'Bid',
  });

  const handleOpenModal = ({ fieldToUpdate, type, playerName }) => {
    setModalState({
      isOpen: true,
      fieldToUpdate,
      playerName,
      type,
    });
  };

  const handleCloseModal = () => {
    setModalState((prev) => ({ ...prev, isOpen: false }));
  };

  const renderPlayer = (position) => {
    // Base props map
    const propsMap = {
        bottom: { 
            name: t1p1Name, 
            team: 'team1', 
            bid: team1BidsAndActuals.p1Bid, 
            actual: team1BidsAndActuals.p1Actual,
            bidField: 'team1BidsAndActuals.p1Bid',
            actualField: 'team1BidsAndActuals.p1Actual',
            dealer: 'team1BidsAndActuals.p1Bid' // Dealer associated with bid usually
        },
        top: { 
            name: t1p2Name, 
            team: 'team1', 
            bid: team1BidsAndActuals.p2Bid, 
            actual: team1BidsAndActuals.p2Actual,
            bidField: 'team1BidsAndActuals.p2Bid',
            actualField: 'team1BidsAndActuals.p2Actual',
            dealer: 'team1BidsAndActuals.p2Bid'
        },
        left: { 
            name: t2p1Name, 
            team: 'team2', 
            bid: team2BidsAndActuals.p1Bid, 
            actual: team2BidsAndActuals.p1Actual,
            bidField: 'team2BidsAndActuals.p1Bid',
            actualField: 'team2BidsAndActuals.p1Actual',
            dealer: 'team2BidsAndActuals.p1Bid'
        },
        right: { 
            name: t2p2Name, 
            team: 'team2', 
            bid: team2BidsAndActuals.p2Bid, 
            actual: team2BidsAndActuals.p2Actual,
            bidField: 'team2BidsAndActuals.p2Bid',
            actualField: 'team2BidsAndActuals.p2Actual',
            dealer: 'team2BidsAndActuals.p2Bid'
        },
    };

    const data = propsMap[position];

    // Determine Logic
    const isBidPhase = !allBidsEntered;
    const type = isBidPhase ? 'Bid' : 'Actual';
    const playerInput = isBidPhase ? data.bid : data.actual;
    const fieldToUpdate = isBidPhase ? data.bidField : data.actualField;

    return (
      <TablePlayerInput
        playerName={data.name}
        teamClassName={data.team}
        playerInput={playerInput}
        type={type}
        fieldToUpdate={fieldToUpdate}
        dealerId={data.dealer}
        isCurrent={isCurrent}
        roundHistory={roundHistory}
        currentRound={currentRound}
        index={roundIndex}
        onOpenModal={handleOpenModal}
        showBid={allBidsEntered}
        bidDisplay={data.bid}
        bidField={data.bidField}
      />
    );
  };

  return (
    <Box position="relative" w="100%" h="400px" my={4} data-cy="table-round">
      <ErrorModal
        isOpen={!isValid}
        setIsModalOpen={setIsValid}
        index={roundIndex}
        names={names}
        isCurrent={isCurrent}
        roundHistory={roundHistory}
        currentRound={currentRound}
        errorMessage={getActualsErrorText(totalActuals)}
      />

      {/* Hoisted Input Modal */}
      <InputModal
        isCurrent={isCurrent}
        playerName={modalState.playerName}
        isOpen={modalState.isOpen}
        setIsModalOpen={handleCloseModal} 
        type={modalState.type}
        fieldToUpdate={modalState.fieldToUpdate}
        currentRound={currentRound}
        roundHistory={roundHistory}
        index={roundIndex}
      />
      
      {/* Table Image / Background */}
      <Box
        position="absolute"
        top="50%"
        left="50%"
        transform="translate(-50%, -50%)"
        w="70%"
        h="60%"
        border="4px solid"
        borderColor="whiteAlpha.300"
        borderRadius="full"
        zIndex={0}
      />

      {/* Team 1 Game Score - Top Left */}
      <Box position="absolute" top="0" left="0" zIndex={10}>
          <GameScoreDisplay 
            teamName={team1Name || 'Team 1'}
            score={team1Score.teamScore}
            bags={team1Score.teamBags}
            teamClassName="team1"
          />
      </Box>

      {/* Team 2 Game Score - Top Right */}
      <Box position="absolute" top="0" right="0" zIndex={10}>
          <GameScoreDisplay 
            teamName={team2Name || 'Team 2'}
            score={team2Score.teamScore}
            bags={team2Score.teamBags}
            teamClassName="team2"
          />
      </Box>

      {/* Team 1 Round Totals - Bottom Left */}
      <Box position="absolute" bottom="0" left="0" zIndex={10}>
        <TeamTotalDisplay
            teamName={team1Name || 'Team 1'}
            bidTotal={team1TotalBid}
            actualTotal={addInputs(team1BidsAndActuals.p1Actual, team1BidsAndActuals.p2Actual)}
            isActualsPhase={allBidsEntered}
            teamClassName="team1"
            isAuto={currentRound?.autoGeneratedActuals?.team1P1 || currentRound?.autoGeneratedActuals?.team1P2}
            onOpenModal={() => handleOpenModal({
                fieldToUpdate: 'team1Total', 
                type: 'Actual',
                playerName: team1Name || 'Team 1'
            })}
        />
      </Box>

      {/* Team 2 Round Totals - Bottom Right */}
      <Box position="absolute" bottom="0" right="0" zIndex={10}>
        <TeamTotalDisplay
            teamName={team2Name || 'Team 2'}
            bidTotal={team2TotalBid}
            actualTotal={addInputs(team2BidsAndActuals.p1Actual, team2BidsAndActuals.p2Actual)}
            isActualsPhase={allBidsEntered}
            teamClassName="team2"
            isAuto={currentRound?.autoGeneratedActuals?.team2P1 || currentRound?.autoGeneratedActuals?.team2P2}
            onOpenModal={() => handleOpenModal({
                fieldToUpdate: 'team2Total',
                type: 'Actual',
                playerName: team2Name || 'Team 2'
            })}
        />
      </Box>

      {/* Bottom Player (Me) - Order 1 */}
      <Box position="absolute" bottom="0" left="50%" transform="translateX(-50%)" zIndex={10}>
        {renderPlayer('bottom')}
      </Box>

      {/* Left Player (Opponent 1) - Order 2 */}
      <Box position="absolute" top="50%" left="0" transform="translateY(-50%)" zIndex={10}>
        {renderPlayer('left')}
      </Box>

      {/* Top Player (Partner) - Order 3 */}
      <Box position="absolute" top="0" left="50%" transform="translateX(-50%)" zIndex={10}>
        {renderPlayer('top')}
      </Box>

      {/* Right Player (Opponent 2) - Order 4 */}
      <Box position="absolute" top="50%" right="0" transform="translateY(-50%)" zIndex={10}>
         {renderPlayer('right')}
      </Box>
      
      {/* Center Info */}
      <Flex
        position="absolute"
        top="50%"
        left="50%"
        transform="translate(-50%, -50%)"
        direction="column"
        align="center"
        justify="center"
        zIndex={10}
      >
        <Text fontSize="xl" fontWeight="bold">Round {roundIndex + 1}</Text>
        <Unclaimed numUnclaimed={unclaimed} />
        {allBidsEntered && (
           <Text fontSize="xs" color="gray.400" mt={1}>Enter Actuals</Text>
        )}
      </Flex>
    </Box>
  );
}

export default TableRound;
