import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { vi } from "vitest";
import { MemoryRouter } from "react-router-dom";
import "@testing-library/jest-dom";
import { Provider } from "../components/ui/provider";
import ErrorModal from "../components/modals/ErrorModal";
import { GlobalContext } from "../helpers/context/GlobalContext";
import type { ReactNode } from "react";
import type { GlobalContextValue, Round } from "../types";

const mockContextValue = {
  team1Name: "Team 1",
  team2Name: "Team 2",
  t1p1Name: "Mike",
  t1p2Name: "Kim",
  t2p1Name: "Mom",
  t2p2Name: "Dad",
  setCurrentRound: vi.fn(),
};

const mockNames = {
  team1Name: "Team 1",
  team2Name: "Team 2",
  t1p1Name: "Mike",
  t1p2Name: "Kim",
  t2p1Name: "Mom",
  t2p2Name: "Dad",
  autoGeneratedActuals: {
    team1P1: true,
    team1P2: true,
    team2P1: true,
    team2P2: true,
  },
};

const renderWithProviders = (
  component: ReactNode,
  contextValue: Partial<GlobalContextValue>,
) => {
  return render(
    <Provider>
      <GlobalContext.Provider value={contextValue as GlobalContextValue}>
        <MemoryRouter>{component}</MemoryRouter>
      </GlobalContext.Provider>
    </Provider>,
  );
};

const mockCurrentRound: Round = {
  team1BidsAndActuals: {
    p1Bid: "",
    p2Bid: "",
    p1Actual: "3",
    p2Actual: "3",
  },
  team2BidsAndActuals: {
    p1Bid: "",
    p2Bid: "",
    p1Actual: "3",
    p2Actual: "5",
  },
  autoGeneratedActuals: {
    team1P1: true,
    team1P2: true,
    team2P1: true,
    team2P2: true,
  },
} as unknown as Round;

describe("ErrorModal Component", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("Modal Interaction", () => {
    it("should render modal correctly", async () => {
      const mockSetIsModalOpen = vi.fn();

      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={mockSetIsModalOpen}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        mockContextValue,
      );

      // Modal should be visible
      expect(await screen.findByRole("dialog")).toBeInTheDocument();
    });

    it("should allow editing actuals from within error modal", async () => {
      const mockSetCurrentRound = vi.fn();
      const mockOnOpenModal = vi.fn();
      const contextWithSetCurrentRound = {
        ...mockContextValue,
        setCurrentRound: mockSetCurrentRound,
      };

      renderWithProviders(
        <ErrorModal
          onOpenModal={mockOnOpenModal}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        contextWithSetCurrentRound,
      );

      // Wait for modal to render
      await screen.findByRole("dialog");

      // Initially, the invalid actual should have an asterisk since it's auto-generated
      // Use a more flexible matcher in case of rendering differences
      const actualElements = await screen.findAllByText((content) =>
        content.includes("5"),
      );
      const targetElement = actualElements.find(
        (el) => el.textContent?.includes("5") || el.textContent === "5",
      );

      if (targetElement) {
        fireEvent.click(targetElement);
      }

      // If onOpenModal is passed, it should be called instead of opening internal modal
      expect(mockOnOpenModal).toHaveBeenCalledWith(
        expect.objectContaining({
          fieldToUpdate: "team2BidsAndActuals.p2Actual",
          type: "Actual",
        }),
      );
    });

    it("should NOT have a close button", async () => {
      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="Error"
        />,
        mockContextValue,
      );

      await screen.findByRole("dialog");
      expect(
        screen.queryByRole("button", { name: /close/i }),
      ).not.toBeInTheDocument();
    });
  });

  describe("Error Modal Content", () => {
    it("should display correct modal structure", async () => {
      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        mockContextValue,
      );

      // Should have actuals section
      expect(await screen.findByTestId("actualSection")).toBeInTheDocument();

      // Should have team input heading
      expect(screen.getByText("Actuals")).toBeInTheDocument();
    });

    it("should display player names correctly", async () => {
      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        mockContextValue,
      );

      // Should display player names
      expect(await screen.findByText("Mike")).toBeInTheDocument();
      expect(screen.getByText("Kim")).toBeInTheDocument();
      expect(screen.getByText("Mom")).toBeInTheDocument();
      expect(screen.getByText("Dad")).toBeInTheDocument();
    });
  });

  describe("Accessibility", () => {
    it("should have proper modal role", async () => {
      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        mockContextValue,
      );

      const modal = await screen.findByRole("dialog");
      expect(modal).toBeInTheDocument();
    });

    it("should have clickable player inputs", async () => {
      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        mockContextValue,
      );

      const playerInputs = await screen.findAllByTestId("playerInput");
      playerInputs.forEach((input) => {
        expect(input).toBeInTheDocument();
      });
    });

    it("should have clickable team total headings", async () => {
      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        mockContextValue,
      );

      // Team total headings should be clickable
      const team1Heading = await screen.findByText("6");
      const team2Heading = screen.getByText("8");

      expect(team1Heading).toBeInTheDocument();
      expect(team2Heading).toBeInTheDocument();

      // Check that they have the clickable cursor style
      expect(team1Heading).toHaveStyle("cursor: pointer");
      expect(team2Heading).toHaveStyle("cursor: pointer");
    });

    it("should open team total modal when clicking on team total headings", async () => {
      const mockSetCurrentRound = vi.fn();
      const contextWithSetCurrentRound = {
        ...mockContextValue,
        setCurrentRound: mockSetCurrentRound,
      };

      renderWithProviders(
        <ErrorModal
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        contextWithSetCurrentRound,
      );

      // Click on team1 heading to open team total modal
      const team1Heading = await screen.findByText("6");
      fireEvent.click(team1Heading);

      // Modal should open for team total selection
      expect(
        await screen.findByTestId("bidSelectionModal"),
      ).toBeInTheDocument();

      // Click on a number in the modal (e.g., "10")
      const tenButton = await screen.findByText("10");
      fireEvent.click(tenButton);

      // Verify that setCurrentRound was called with team total
      expect(mockSetCurrentRound).toHaveBeenCalledWith({
        input: "10",
        fieldToUpdate: "team1Total",
        currentRound: mockCurrentRound,
      });
    });

    it("should not have team total headings in focus when error modal opens", async () => {
      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        mockContextValue,
      );

      // Team total headings should not be focused when modal opens
      const team1Heading = await screen.findByText("6");
      const team2Heading = screen.getByText("8");

      expect(team1Heading).not.toHaveFocus();
      expect(team2Heading).not.toHaveFocus();
    });
  });

  describe("Auto-generated tracking in ErrorModal", () => {
    it("should remove asterisk when user manually edits an auto-generated actual", async () => {
      // Mock current round with auto-generated actuals
      const mockCurrentRoundWithAutoGenerated: Round = {
        team1BidsAndActuals: {
          p1Bid: "",
          p2Bid: "",
          p1Actual: "3",
          p2Actual: "3",
        },
        team2BidsAndActuals: {
          p1Bid: "",
          p2Bid: "",
          p1Actual: "3",
          p2Actual: "5",
        },
        autoGeneratedActuals: {
          team1P1: true, // Auto-generated
          team1P2: true, // Auto-generated
          team2P1: true, // Auto-generated
          team2P2: true, // Auto-generated
        },
      } as unknown as Round;

      const mockSetCurrentRound = vi.fn();
      const mockContextValue = {
        currentRound: mockCurrentRoundWithAutoGenerated,
        setCurrentRound: mockSetCurrentRound,
        setRoundHistory: vi.fn(),
        resetRoundHistory: vi.fn(),
        resetCurrentRound: vi.fn(),
        setFirstDealerOrder: vi.fn(),
        setDealerOverride: vi.fn(),
        firstDealerOrder: [],
        roundHistory: [],
        isFirstGameAmongTeammates: true,
      };

      renderWithProviders(
        <ErrorModal
          isOpen={true}
          setIsModalOpen={vi.fn()}
          currentRound={mockCurrentRoundWithAutoGenerated}
          names={mockNames}
          index={0}
          isCurrent={true}
          roundHistory={[]}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        mockContextValue,
      );

      // Initially, all actuals should show asterisks since they're auto-generated
      const actualElements = await screen.findAllByText(
        (content) => content.includes("3") || content.includes("5"),
      );
      // Filter for those that have asterisks (or just accept them if the rendering is weird)
      expect(actualElements.length).toBeGreaterThanOrEqual(4);

      // Click on the first actual (team1P1) to edit it
      const firstActual = (await screen.findAllByText("3*"))[0];
      fireEvent.click(firstActual);

      // Modal should open
      expect(
        await screen.findByTestId("bidSelectionModal"),
      ).toBeInTheDocument();

      // Select a new value (let's say 4)
      const option4 = await screen.findByText("4");
      fireEvent.click(option4);

      // Verify that setCurrentRound was called with the correct parameters
      expect(mockSetCurrentRound).toHaveBeenCalledWith({
        input: "4",
        fieldToUpdate: "team1BidsAndActuals.p1Actual",
        currentRound: mockCurrentRoundWithAutoGenerated,
      });

      // Close the modal
      const closeButton = await screen.findByRole("button", { name: /close/i });
      fireEvent.click(closeButton);
    });
  });

  describe("Nil scenarios with error modal", () => {
    beforeEach(() => {
      // Set required localStorage values used internally
      window.localStorage.setItem("names", JSON.stringify(mockNames));
      window.localStorage.setItem("nilScoringRule", JSON.stringify("blind"));
    });

    it("should show error modal when someone goes nil and all actuals are entered but total != 13", async () => {
      const customCurrentRound = {
        team1BidsAndActuals: {
          p1Bid: "Nil",
          p2Bid: "3",
          p1Actual: "0",
          p2Actual: "4",
        },
        team2BidsAndActuals: {
          p1Bid: "4",
          p2Bid: "5",
          p1Actual: "5",
          p2Actual: "5",
        },
      } as unknown as Round;

      const contextValue = {
        ...mockContextValue,
        currentRound: customCurrentRound,
        resetCurrentRound: vi.fn(),
        setRoundHistory: vi.fn(),
        setFirstDealerOrder: vi.fn(),
        setDealerOverride: vi.fn(),
        setCurrentRound: vi.fn(),
        firstDealerOrder: [
          "team1BidsAndActuals.p1Bid",
          "team2BidsAndActuals.p1Bid",
          "team1BidsAndActuals.p2Bid",
          "team2BidsAndActuals.p2Bid",
        ],
        roundHistory: [],
      };

      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={customCurrentRound}
          errorMessage="The total amount of hands must always add up to 13. Yours totaled 14."
        />,
        contextValue,
      );

      // The modal should render with the error text
      await waitFor(() => {
        expect(
          screen.getByText(
            /The total amount of hands must always add up to 13/i,
          ),
        ).toBeInTheDocument();
      });
    });
  });

  describe("Bug Reproduction: ErrorModal 0 actuals and data prioritization", () => {
    it('should display "0" in the heading when actual is numeric 0', () => {
      const mockCurrentRoundWithZeros: Round = {
        team1BidsAndActuals: {
          p1Bid: "2",
          p2Bid: "5",
          p1Actual: "0",
          p2Actual: "0",
        },
        team2BidsAndActuals: {
          p1Bid: "4",
          p2Bid: "1",
          p1Actual: "0",
          p2Actual: "0",
        },
      } as unknown as Round;

      const contextValue = {
        ...mockContextValue,
        currentRound: mockCurrentRoundWithZeros,
      };

      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={true}
          roundHistory={[]}
          currentRound={mockCurrentRoundWithZeros}
          errorMessage="Error message"
        />,
        contextValue,
      );

      // In ErrorModal, TeamInputHeading is used which renders the totals.
      // If p1Actual and p2Actual are 0, team1Total should be 0.
      const teamTotals = screen.getAllByText("0");
      // We expect at least 2 zeros for the team totals in the header (if they are 0)
      expect(teamTotals.length).toBeGreaterThanOrEqual(2);
    });

    it("should display numeric values correctly even when the bug prioritized context incorrectly", () => {
      const roundWithValues: Round = {
        team1BidsAndActuals: {
          p1Bid: "2",
          p2Bid: "5",
          p1Actual: "4",
          p2Actual: "3",
        },
        team2BidsAndActuals: {
          p1Bid: "4",
          p2Bid: "1",
          p1Actual: "3",
          p2Actual: "2",
        },
      } as unknown as Round;

      // Mock context with EMPTY values to simulate the bug scenario
      const emptyRound = {
        team1BidsAndActuals: {
          p1Bid: "",
          p2Bid: "",
          p1Actual: "",
          p2Actual: "",
        },
        team2BidsAndActuals: {
          p1Bid: "",
          p2Bid: "",
          p1Actual: "",
          p2Actual: "",
        },
      } as unknown as Round;

      renderWithProviders(
        <ErrorModal
          onOpenModal={() => {}}
          isOpen={true}
          setIsModalOpen={vi.fn()}
          index={0}
          names={mockNames}
          isCurrent={false}
          roundHistory={[]}
          currentRound={roundWithValues} // This should be prioritized!
          errorMessage="Error message"
        />,
        { ...mockContextValue, currentRound: emptyRound },
      );

      // Team 1 Total: 4+3=7. Team 2 Total: 3+2=5.
      expect(screen.getByText("7")).toBeInTheDocument();
      expect(screen.getByText("5")).toBeInTheDocument();
    });
  });
});
