import { vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import { Provider } from '../components/ui/provider';
import SpadesCalculator from '../pages/SpadesCalculator';
import { GlobalContext } from '../store/GlobalContext';
import { createMockGlobalContext } from './utils/mockContext';
import { EMPTY_ROUND } from '../helpers/utils/constants';
import type { GlobalContextValue, Round, WinAcknowledgement } from '../types';

const { mockedNavigate } = vi.hoisted(() => ({
  mockedNavigate: vi.fn(),
}));

vi.mock('react-router-dom', async (importOriginal) => {
  const actual = (await importOriginal()) as Record<string, unknown>;
  return {
    ...actual,
    useNavigate: () => mockedNavigate,
  };
});

const renderWithProviders = (
  component: React.ReactNode,
  contextValue: GlobalContextValue,
) => {
  return render(
    <BrowserRouter>
      <Provider>
        <GlobalContext.Provider value={contextValue}>
          {component}
        </GlobalContext.Provider>
      </Provider>
    </BrowserRouter>,
  );
};

// Four completed rounds: Team 1 makes 13 each round (+130), Team 2 goes set
// each round (-20). Totals: team1 520, team2 -80.
const winningRoundHistory: Round[] = [0, 1, 2, 3].map(() => ({
  team1BidsAndActuals: {
    p1Bid: '8',
    p2Bid: '5',
    p1Actual: '8',
    p2Actual: '5',
  },
  team2BidsAndActuals: {
    p1Bid: '1',
    p2Bid: '1',
    p1Actual: '0',
    p2Actual: '0',
  },
  dealerOverride: null,
  autoGeneratedActuals: {
    team1P1: false,
    team1P2: false,
    team2P1: false,
    team2P2: false,
  },
}));

const boardContext = (overrides: Partial<GlobalContextValue> = {}) =>
  createMockGlobalContext({
    scoreLimit: 500,
    roundHistory: winningRoundHistory,
    currentRound: EMPTY_ROUND,
    firstDealerOrder: [
      'team1BidsAndActuals.p1Bid',
      'team2BidsAndActuals.p1Bid',
      'team1BidsAndActuals.p2Bid',
      'team2BidsAndActuals.p2Bid',
    ],
    ...overrides,
  }) as GlobalContextValue;

const currentSnapshot = (): WinAcknowledgement => ({
  team1: 520,
  team2: -80,
  scoreLimit: 500,
});

describe('game-end acknowledgement', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockedNavigate.mockClear();
    window.localStorage.clear();
  });

  it('suppresses the announcement when the persisted acknowledgement matches the current outcome', async () => {
    // Simulates returning to the page after dismissing: a fresh mount reads
    // the acknowledgement from context and must not resurrect the modal.
    const contextValue = boardContext({ winAcknowledged: currentSnapshot() });
    renderWithProviders(<SpadesCalculator />, contextValue);

    await screen.findAllByText('Team 1');
    expect(screen.queryByText('Game Over')).not.toBeInTheDocument();
    expect(screen.queryByTestId('game-won-modal')).not.toBeInTheDocument();
  });

  it('re-announces when new play changes the scores after acknowledgement', async () => {
    // One more completed round: team1 650, team2 -100 — the stale snapshot
    // no longer matches, so the over-limit game is announced again.
    const contextValue = boardContext({
      winAcknowledged: currentSnapshot(),
      roundHistory: [...winningRoundHistory, winningRoundHistory[0]],
    });
    renderWithProviders(<SpadesCalculator />, contextValue);

    expect(await screen.findByText('Game Over')).toBeInTheDocument();
    expect(screen.getByText('Team 1 wins!')).toBeInTheDocument();
  });

  it('re-announces when the acknowledged snapshot was taken under a different limit', async () => {
    const contextValue = boardContext({
      scoreLimit: 400,
      winAcknowledged: currentSnapshot(),
    });
    renderWithProviders(<SpadesCalculator />, contextValue);

    expect(await screen.findByText('Game Over')).toBeInTheDocument();
  });

  it('stores the (team1, team2, scoreLimit) snapshot when the announcement is dismissed', async () => {
    const contextValue = boardContext();
    renderWithProviders(<SpadesCalculator />, contextValue);

    fireEvent.click(await screen.findByRole('button', { name: 'Continue' }));
    fireEvent.click(await screen.findByRole('button', { name: 'No' }));

    await waitFor(() => {
      expect(contextValue.setWinAcknowledged).toHaveBeenCalledWith(
        currentSnapshot(),
      );
    });
    // "No" on the new-limit prompt also wipes the limit.
    expect(contextValue.setScoreLimit).toHaveBeenCalledWith(null);
  });
});
