import { vi } from 'vitest';
import { render, screen, fireEvent, within } from '@testing-library/react';
import { Provider } from '../components/ui/provider';
import ScoreLimitDisplay from '../components/game/ScoreLimitDisplay';
import { GlobalContext } from '../store/GlobalContext';
import { createMockGlobalContext } from './utils/mockContext';
import type { GlobalContextValue, Round } from '../types';

// Four completed rounds: Team 1 makes 13 each round (+130 → 520), Team 2 goes
// set each round (-20 → -80).
const winningRoundHistory: Round[] = [0, 1, 2, 3].map(() => ({
  team1BidsAndActuals: {
    p1Bid: '8',
    p2Bid: '5',
    p1Actual: '8',
    p2Actual: '5',
  },
  team2BidsAndActuals: {
    p1Bid: '1',
    p2Bid: '1',
    p1Actual: '0',
    p2Actual: '0',
  },
  dealerOverride: null,
  autoGeneratedActuals: {
    team1P1: false,
    team1P2: false,
    team2P1: false,
    team2P2: false,
  },
}));

const renderDisplay = (overrides: Partial<GlobalContextValue> = {}) => {
  const contextValue = createMockGlobalContext(overrides) as GlobalContextValue;
  render(
    <Provider>
      <GlobalContext.Provider value={contextValue}>
        <ScoreLimitDisplay />
      </GlobalContext.Provider>
    </Provider>,
  );
  return { contextValue };
};

describe('ScoreLimitDisplay', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    window.localStorage.clear();
  });

  it('shows the score limit as a native button so keyboard users can reach it', () => {
    renderDisplay({ scoreLimit: 500 });

    const display = screen.getByTestId('score-limit-display');
    // A native <button> gets Enter/Space activation (and focusability) for
    // free — the whole point of the a11y fix over a clickable <Text>.
    expect(display.tagName).toBe('BUTTON');
    expect(display).toHaveTextContent('Score limit: 500');
    expect(display).toHaveAttribute('aria-disabled', 'false');
  });

  it('opens the edit modal when clicked and saves the new limit', async () => {
    const { contextValue } = renderDisplay({ scoreLimit: 500 });

    fireEvent.click(screen.getByTestId('score-limit-display'));
    const modal = await screen.findByTestId('edit-score-limit-modal');
    expect(modal).toHaveTextContent('Edit Score Limit');

    fireEvent.change(screen.getByTestId('score-limit-input'), {
      target: { value: '600' },
    });
    fireEvent.click(screen.getByTestId('setScoreLimitButton'));

    expect(contextValue.setScoreLimit).toHaveBeenCalledWith(600);
  });

  it('says "Set Score Limit" when no limit exists yet', async () => {
    renderDisplay({ scoreLimit: null, roundHistory: [] });

    expect(
      screen.getByTestId('score-limit-display'),
    ).toHaveTextContent('Score limit: ∞');

    fireEvent.click(screen.getByTestId('score-limit-display'));
    const modal = await screen.findByTestId('edit-score-limit-modal');
    expect(modal).toHaveTextContent('Set Score Limit');
  });

  it('is inert for viewers', async () => {
    renderDisplay({ scoreLimit: 500, role: 'viewer' as const });

    const display = screen.getByTestId('score-limit-display');
    expect(display).toHaveAttribute('aria-disabled', 'true');
    expect(display).toHaveTextContent('Score limit: 500');

    fireEvent.click(display);
    await new Promise((resolve) => setTimeout(resolve, 50));
    expect(
      screen.queryByTestId('edit-score-limit-modal'),
    ).not.toBeInTheDocument();
  });

  it('floors the replacement limit at the would-be winner score', async () => {
    // Team 1 has 520 banked against a 500 limit — a replacement must beat 520.
    renderDisplay({
      scoreLimit: 500,
      roundHistory: winningRoundHistory,
    });

    fireEvent.click(screen.getByTestId('score-limit-display'));
    const modal = await screen.findByTestId('edit-score-limit-modal');

    const input = within(modal).getByTestId(
      'score-limit-input',
    ) as HTMLInputElement;
    fireEvent.change(input, { target: { value: '520' } });
    expect(
      await within(modal).findByText('Must be higher than 520'),
    ).toBeInTheDocument();
  });
});
