import { renderHook } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import { useGameScores, useFinishedGameScores } from '../helpers/utils/hooks';
import { GlobalContext } from '../store/GlobalContext';
import { createMockGlobalContext } from './utils/mockContext';
import { EMPTY_ROUND } from '../helpers/utils/constants';
import type { GlobalContextValue, Round } from '../types';

// One completed round: Team 1 makes 13 (+130), Team 2 goes set (-20).
const completedRound: Round = {
  team1BidsAndActuals: {
    p1Bid: '8',
    p2Bid: '5',
    p1Actual: '8',
    p2Actual: '5',
  },
  team2BidsAndActuals: {
    p1Bid: '1',
    p2Bid: '1',
    p1Actual: '0',
    p2Actual: '0',
  },
  dealerOverride: null,
  autoGeneratedActuals: {
    team1P1: false,
    team1P2: false,
    team2P1: false,
    team2P2: false,
  },
};

// Every bid/actual entered but actuals total 12, not 13 — display counts it,
// finished scores must not.
const wrongTotalRound: Round = {
  team1BidsAndActuals: {
    p1Bid: '5',
    p2Bid: '5',
    p1Actual: '5',
    p2Actual: '5',
  },
  team2BidsAndActuals: {
    p1Bid: '1',
    p1Actual: '1',
    p2Bid: '1',
    p2Actual: '1',
  },
  dealerOverride: null,
  autoGeneratedActuals: {
    team1P1: false,
    team1P2: false,
    team2P1: false,
    team2P2: false,
  },
};

const renderScores = (overrides: Partial<GlobalContextValue> = {}) => {
  const contextValue = createMockGlobalContext(overrides) as GlobalContextValue;
  return renderHook(
    () => ({
      display: useGameScores(),
      finished: useFinishedGameScores(),
    }),
    {
      wrapper: ({ children }) => (
        <GlobalContext.Provider value={contextValue}>
          {children}
        </GlobalContext.Provider>
      ),
    },
  );
};

describe('useFinishedGameScores', () => {
  it('sums completed round history', () => {
    const { result } = renderScores({
      roundHistory: [completedRound],
      currentRound: EMPTY_ROUND,
    });

    expect(result.current.finished).toEqual({ team1: 130, team2: -20 });
  });

  it('excludes a completed-inputs round whose actuals do not total 13', () => {
    const { result } = renderScores({
      roundHistory: [completedRound],
      currentRound: wrongTotalRound,
    });

    // Finished: history only. Display: history plus the in-progress round
    // (Team 1 +100, Team 2 +20).
    expect(result.current.finished).toEqual({ team1: 130, team2: -20 });
    expect(result.current.display.team1Score.teamScore).toBe(230);
    expect(result.current.display.team2Score.teamScore).toBe(0);
  });

  it('excludes a round with an empty actual', () => {
    const partialRound: Round = {
      team1BidsAndActuals: {
        p1Bid: '5',
        p2Bid: '5',
        p1Actual: '5',
        p2Actual: '5',
      },
      team2BidsAndActuals: {
        p1Bid: '1',
        p2Bid: '1',
        p1Actual: '2',
        p2Actual: '',
      },
      dealerOverride: null,
      autoGeneratedActuals: {
        team1P1: false,
        team1P2: false,
        team2P1: false,
        team2P2: false,
      },
    };

    const { result } = renderScores({
      roundHistory: [completedRound],
      currentRound: partialRound,
    });

    expect(result.current.finished).toEqual({ team1: 130, team2: -20 });
  });

  it('includes the current round once it is actually complete', () => {
    const { result } = renderScores({
      roundHistory: [completedRound],
      currentRound: completedRound,
    });

    expect(result.current.finished).toEqual({ team1: 260, team2: -40 });
  });

  it('reads the viewer perspective fields for viewers', () => {
    const { result } = renderScores({
      role: 'viewer' as const,
      roundHistory: [],
      currentRound: EMPTY_ROUND,
      viewRoundHistory: [completedRound],
      viewCurrentRound: EMPTY_ROUND,
    });

    expect(result.current.finished).toEqual({ team1: 130, team2: -20 });
  });

  it('sums to zero for a brand-new game', () => {
    const { result } = renderScores({
      roundHistory: [],
      currentRound: EMPTY_ROUND,
    });

    expect(result.current.finished).toEqual({ team1: 0, team2: 0 });
  });
});
