import { describe, it, beforeEach, expect, vi } from 'vitest';
import { render, waitFor, act } from '@testing-library/react';
import { useContext, useEffect, useRef } from 'react';
import { StateProvider, GlobalContext } from '../store/GlobalContext';
import type { GlobalContextValue, AppState, Round, InputValue } from '../types';

const { subscribeSessionMock } = vi.hoisted(() => ({
  subscribeSessionMock: vi.fn(),
}));

vi.mock('../firebase/realtime', () => ({
  isRealtimeEnabled: vi.fn(() => false),
  createSession: vi.fn(),
  writeSessionState: vi.fn(),
  subscribeSession: subscribeSessionMock,
}));

let ctx: GlobalContextValue;

function ViewerHarness({ id }: { id: string }) {
  const value = useContext(GlobalContext);
  const joinedRef = useRef(false);

  useEffect(() => {
    ctx = value;
  }, [value]);

  useEffect(() => {
    if (joinedRef.current) return;
    joinedRef.current = true;
    value.joinSession(id);
  }, [value, id]);

  return null;
}

// The leader's canonical board, where "me" sits at t1p1 (the "you" slot) and
// "dad" sits at t2p1 (team 2, left opponent).
const leaderNames = {
  team1Name: 'Us',
  team2Name: 'Them',
  t1p1Name: 'me',
  t1p2Name: 'partner',
  t2p1Name: 'dad',
  t2p2Name: 'mom',
};

// The viewer's OWN local game, where "dad" sits at t1p1 on this device.
const localNames = {
  team1Name: 'My Team',
  team2Name: 'Their Team',
  t1p1Name: 'dad',
  t1p2Name: 'brother',
  t2p1Name: 'me',
  t2p2Name: 'sister',
};

type RoundArgs = {
  team1: { p1Bid: InputValue; p2Bid: InputValue; p1Actual: InputValue; p2Actual: InputValue };
  team2: { p1Bid: InputValue; p2Bid: InputValue; p1Actual: InputValue; p2Actual: InputValue };
  dealerOverride?: string | null;
};

const round = ({ team1, team2, dealerOverride }: RoundArgs): Round => ({
  team1BidsAndActuals: { ...team1 },
  team2BidsAndActuals: { ...team2 },
  dealerOverride: dealerOverride ?? null,
});

const leaderState: AppState = {
  currentRound: {
    team1BidsAndActuals: { p1Bid: '2', p2Bid: '4', p1Actual: '', p2Actual: '' },
    team2BidsAndActuals: { p1Bid: '6', p2Bid: '8', p1Actual: '', p2Actual: '' },
    dealerOverride: 'team2BidsAndActuals.p1Bid', // dad (t2p1) is dealer
    autoGeneratedActuals: {
      team1P1: false,
      team1P2: false,
      team2P1: false,
      team2P2: false,
    },
  },
  roundHistory: [
    round({
      team1: { p1Bid: '5', p2Bid: '6', p1Actual: '5', p2Actual: '6' },
      team2: { p1Bid: '7', p2Bid: '8', p1Actual: '7', p2Actual: '8' },
    }),
    round({
      team1: { p1Bid: '1', p2Bid: '2', p1Actual: '1', p2Actual: '2' },
      team2: { p1Bid: '3', p2Bid: '4', p1Actual: '3', p2Actual: '4' },
      dealerOverride: 'team1BidsAndActuals.p2Bid', // partner is dealer
    }),
  ],
  firstDealerOrder: [
    'team1BidsAndActuals.p1Bid',
    'team2BidsAndActuals.p1Bid',
    'team1BidsAndActuals.p2Bid',
    'team2BidsAndActuals.p2Bid',
  ],
  isFirstGameAmongTeammates: true,
  names: leaderNames,
  nilScoringRule: 'takesBags',
  scoreLimit: null,
};

describe('viewer leave', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    subscribeSessionMock.mockReturnValue(() => {});
    window.localStorage.clear();
    window.sessionStorage.clear();
  });

  it("restores the viewer's own local names when this device has its own game", async () => {
    // Seed this device's own local game.
    window.localStorage.setItem('names', JSON.stringify(localNames));

    render(
      <StateProvider>
        <ViewerHarness id="s1" />
      </StateProvider>,
    );

    await waitFor(() => expect(subscribeSessionMock).toHaveBeenCalled());

    const onData = subscribeSessionMock.mock.calls[0][1];
    act(() => onData(leaderState));

    await waitFor(() => expect(ctx.names.t1p1Name).toBe('me'));

    act(() => ctx.endSession());

    expect(ctx.names.t1p1Name).toBe('dad');
    expect(ctx.names).toEqual(localNames);
  });

  it("seeds the viewer's own full game, rotated to their seat, when there is no local game", async () => {
    render(
      <StateProvider>
        <ViewerHarness id="s1" />
      </StateProvider>,
    );

    await waitFor(() => expect(subscribeSessionMock).toHaveBeenCalled());

    const onData = subscribeSessionMock.mock.calls[0][1];
    act(() => onData(leaderState));

    await waitFor(() => expect(ctx.names.t1p1Name).toBe('me'));

    // The viewer identifies as "dad" — t2p1 on the leader's board.
    act(() => ctx.setSeat('t2p1'));
    await waitFor(() => expect(ctx.seat).toBe('t2p1'));

    act(() => ctx.endSession());

    // Names rotate so "dad" (the viewer's seat) lands in the "you" (t1p1) slot.
    expect(ctx.names.t1p1Name).toBe('dad');
    expect(ctx.names.t2p2Name).toBe('me');
    // Team 2 viewers see the team labels swapped.
    expect(ctx.names.team1Name).toBe('Them');
    expect(ctx.names.team2Name).toBe('Us');

    // The FULL game data must survive the leave — not reset to a fresh game.
    expect(ctx.roundHistory).toHaveLength(2);
    // History round 0 (leader bids 5/6/7/8): dad's bid moves to the "you" slot.
    expect(ctx.roundHistory[0].team1BidsAndActuals.p1Bid).toBe('7');
    expect(ctx.roundHistory[0].team2BidsAndActuals.p2Bid).toBe('5');
    // History round 1 carried a dealer override (partner = t1p2); it rotates.
    expect(ctx.roundHistory[1].dealerOverride).toBe('team2BidsAndActuals.p1Bid');

    // Current round is preserved and rotated, including its dealer override.
    expect(ctx.currentRound.team1BidsAndActuals.p1Bid).toBe('6');
    expect(ctx.currentRound.team2BidsAndActuals.p1Bid).toBe('4');
    expect(ctx.currentRound.dealerOverride).toBe('team1BidsAndActuals.p1Bid');

    // firstDealerOrder is a per-player fact and must rotate too.
    expect(ctx.firstDealerOrder).toEqual([
      'team2BidsAndActuals.p2Bid',
      'team1BidsAndActuals.p1Bid',
      'team2BidsAndActuals.p1Bid',
      'team1BidsAndActuals.p2Bid',
    ]);

    // Game-level settings are shared verbatim.
    expect(ctx.isFirstGameAmongTeammates).toBe(true);
    expect(ctx.nilScoringRule).toBe('takesBags');
  });
});
