// ─────────────────────────────────────────────────────────────────────────────
// Domain types shared across the Spades Calculator app
// ─────────────────────────────────────────────────────────────────────────────

export type BidValue =
  | "Blind Nil"
  | "Nil"
  | "1"
  | "2"
  | "3"
  | "4"
  | "5"
  | "6"
  | "7"
  | "8"
  | "9"
  | "10"
  | "11"
  | "12"
  | "13";

export type ActualValue =
  | 0
  | "1"
  | "2"
  | "3"
  | "4"
  | "5"
  | "6"
  | "7"
  | "8"
  | "9"
  | "10"
  | "11"
  | "12"
  | "13";

export type InputValue = string | number;

export type NilSetting = "takesBags" | "helpsTeamBid" | "noBagsNoHelp";

export type TeamKey = "team1BidsAndActuals" | "team2BidsAndActuals";

// ─── Player / team bids & actuals ────────────────────────────────────────────

export interface TeamBidsAndActuals {
  p1Bid: InputValue;
  p2Bid: InputValue;
  p1Actual: InputValue;
  p2Actual: InputValue;
}

export interface AutoGeneratedActuals {
  team1P1: boolean;
  team1P2: boolean;
  team2P1: boolean;
  team2P2: boolean;
}

// ─── Round ───────────────────────────────────────────────────────────────────

export interface Round {
  team1BidsAndActuals: TeamBidsAndActuals;
  team2BidsAndActuals: TeamBidsAndActuals;
  dealerOverride?: string | null;
  autoGeneratedActuals?: AutoGeneratedActuals;
}

// ─── Names ───────────────────────────────────────────────────────────────────

export interface Names {
  t1p1Name: string;
  t1p2Name: string;
  t2p1Name: string;
  t2p2Name: string;
  team1Name: string;
  team2Name: string;
}

// ─── Scoring ─────────────────────────────────────────────────────────────────

export interface TeamScore {
  teamScore: number;
  teamBags: number;
}

export interface RoundScore {
  score: number;
  bags: number;
}

export interface TeamStats {
  startScore: number;
  endScore: number;
  startBags: number;
  endBags: number;
  pointsGained: number;
  bagPenalty: number;
  setPenalty: number;
  nilPenalty: number;
  blindNilPenalty: number;
  netChange: number;
}

// ─── Global store state ────────────────────────────────────────────────────

export interface AppState {
  currentRound: Round;
  roundHistory: Round[];
  firstDealerOrder: string[];
  isFirstGameAmongTeammates: boolean;
}

// ─── Reducer actions ──────────────────────────────────────────────────────

export type AppAction =
  | { type: "SET_CURRENT_ROUND"; payload: { currentRound: Round } }
  | { type: "RESET_CURRENT_ROUND" }
  | { type: "SET_ROUND_HISTORY"; payload: { roundHistory: Round[] } }
  | { type: "RESET_ROUND_HISTORY" }
  | { type: "SET_FIRST_DEALER_ORDER"; payload: { firstDealerOrder: string[] } }
  | { type: "SET_DEALER_OVERRIDE"; payload: { dealerOverride: string | null } };

// ─── Shared UI types ────────────────────────────────────────────────────────
export interface ModalOpenArgs {
  fieldToUpdate: string;
  type: "Bid" | "Actual";
  playerName: string;
  inputId?: string;
  dealerId?: string;
  onCustomUpdate?: (val: InputValue) => void;
}

// ─── Global context value ─────────────────────────────────────────────────

export interface UpdateInputArgs {
  input: InputValue;
  fieldToUpdate: string;
  currentRound: Round;
}

export interface GlobalContextValue {
  currentRound: Round;
  roundHistory: Round[];
  firstDealerOrder: string[];
  isFirstGameAmongTeammates: boolean;
  setCurrentRound: (args: UpdateInputArgs) => void;
  resetCurrentRound: () => void;
  setRoundHistory: (newRoundHistory: Round[]) => void;
  resetRoundHistory: () => void;
  setFirstDealerOrder: (newFirstDealerOrder: string[]) => void;
  setDealerOverride: (dealerOverride: string | null) => void;
}

// ─── Styles ──────────────────────────────────────────────────────────────

export interface TeamColorStyle {
  color: string;
  borderColor: string;
}
