import { useContext, useMemo } from 'react';
import { SimpleGrid, HStack } from '@chakra-ui/react';
import { Button } from './button';
import {
  getButtonValues,
  getEditedRoundHistory,
  updateInput,
} from '../../helpers/utils/helperFunctions';
import { GlobalContext } from '../../store/GlobalContext';
import type { Round, InputValue, TeamBidsAndActuals } from '../../types';

export interface ButtonGridProps {
  type: 'Bid' | 'Actual';
  fieldToUpdate: string;
  currentRound: Round;
  index?: number | string;
  roundHistory?: Round[];
  isCurrent: boolean;
  setIsModalOpen?: (isOpen: boolean) => void;
  onCustomUpdate?: (input: InputValue) => void;
}

function ButtonGrid({
  type,
  fieldToUpdate,
  currentRound,
  index,
  roundHistory,
  isCurrent,
  setIsModalOpen,
  onCustomUpdate,
}: ButtonGridProps) {
  const { setCurrentRound, setRoundHistory } = useContext(GlobalContext);
  const buttonValues = getButtonValues(type);

  // Parse the current field value from the round to determine if Undo should be shown
  const currentValue = useMemo(() => {
    const [teamKey, playerKey] = fieldToUpdate.split('.') as [
      'team1BidsAndActuals' | 'team2BidsAndActuals',
      keyof TeamBidsAndActuals,
    ];
    return currentRound[teamKey]?.[playerKey] ?? '';
  }, [fieldToUpdate, currentRound]);

  const hasValueToUndo = currentValue !== '';

  const onSelect = (input: InputValue) => {
    if (setIsModalOpen) {
      setIsModalOpen(false);
    }

    // If there's a custom update handler, use it instead of the default behavior
    if (onCustomUpdate) {
      onCustomUpdate(input);
      return;
    }

    if (isCurrent) {
      setCurrentRound({
        input,
        fieldToUpdate,
        currentRound: { ...currentRound },
      });
    } else {
      let updatedRound = updateInput({ input, fieldToUpdate, currentRound });

      // If this is an individual actual update, clear auto-generated flag on undo too
      if (fieldToUpdate && fieldToUpdate.includes('Actual')) {
        const teamNumber = fieldToUpdate.includes('team1') ? 1 : 2;
        const playerNumber = fieldToUpdate.includes('p1Actual') ? 'P1' : 'P2';
        const autoGeneratedKey = `team${teamNumber}${playerNumber}`;

        updatedRound = {
          ...updatedRound,
          autoGeneratedActuals: {
            ...updatedRound.autoGeneratedActuals,
            [autoGeneratedKey]: false,
          } as Round['autoGeneratedActuals'],
        };
      }

      const newRoundHistory = getEditedRoundHistory({
        index: index as number,
        updatedRound,
        roundHistory: roundHistory || [],
      });
      setRoundHistory([...newRoundHistory]);
    }
  };

  return (
    <>
      <SimpleGrid columns={3} gap={4}>
        {buttonValues.map((buttonVal, i) => {
          return (
            <Button
              key={i}
              onClick={() => {
                onSelect(buttonVal);
              }}
              data-cy={`${type.toLowerCase()}SelectionButton`}
              variant="secondary"
              whiteSpace="normal"
              h="auto"
              minH="40px"
              py={2}
            >
              {buttonVal}
            </Button>
          );
        })}
      </SimpleGrid>
      {hasValueToUndo && (
        <HStack justify="center" mt={4}>
          <Button
            onClick={() => onSelect('')}
            variant="dangerOutline"
            whiteSpace="normal"
            h="auto"
            minH="40px"
            py={2}
            data-cy="undoSelectionButton"
          >
            Undo
          </Button>
        </HStack>
      )}
    </>
  );
}

export default ButtonGrid;
