import { useState } from 'react';
import { Button, Flex } from '../ui';
import { Pencil } from 'lucide-react';
import { InputModal } from '../modals';
import DealerTag from '../ui/DealerTag';

const PlayerInput = ({
  inputId,
  dealerId,
  type,
  index,
  isCurrent,
  playerName,
  playerInput,
  roundHistory,
  currentRound,
  teamClassName,
  fieldToUpdate,
}) => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  // Check if this specific actual is auto-generated
  const isAutoGenerated = () => {
    if (type !== 'Actual') return false;
    if (!currentRound || !currentRound.autoGeneratedActuals) return false;

    const isTeam1 = fieldToUpdate.includes('team1');
    const isP1 = fieldToUpdate.includes('p1Actual');
    const key = isTeam1
      ? isP1
        ? 'team1P1'
        : 'team1P2'
      : isP1
      ? 'team2P1'
      : 'team2P2';

    return currentRound.autoGeneratedActuals[key] === true;
  };

  const onEdit = () => {
    setIsModalOpen(true);
  };

  // Always show the actual value, with asterisk if auto-generated
  const displayValue =
    playerInput === '' ? '' : `${playerInput}${isAutoGenerated() ? '*' : ''}`;
  const showButton = displayValue === '';

  return (
    <>
      <InputModal
        isCurrent={isCurrent}
        playerName={playerName}
        isOpen={isModalOpen}
        setIsModalOpen={setIsModalOpen}
        type={type}
        fieldToUpdate={fieldToUpdate}
        currentRound={currentRound}
        roundHistory={roundHistory}
        index={index}
      />
      <Flex my={'5px'} direction={'row'} justify={'space-around'}>
        <Flex
          direction={'row'}
          align={'center'}
          style={{ marginRight: '15px' }}
        >
          <span>{playerName}</span>{' '}
          {type === 'Bid' && (
            <DealerTag
              id={dealerId}
              index={index}
              isCurrent={isCurrent}
              roundHistory={roundHistory}
            />
          )}
        </Flex>
        {showButton ? (
          <Button
            onClick={() => {
              setIsModalOpen(true);
            }}
            value={displayValue}
            id={inputId}
            name={inputId}
            size="xs"
            variant={teamClassName === 'team1' ? 'team1Outline' : 'team2Outline'}
            data-cy={type === 'Bid' ? 'bidButton' : 'actualButton'}
            data-testid={type === 'Bid' ? 'bidButton' : 'actualButton'}
          >
            {displayValue || type}
          </Button>
        ) : (
          <div data-cy="playerInput" data-testid="playerInput">
            <Flex
              align="center"
              justify="center"
              cursor="pointer"
              onClick={onEdit}
            >
              <Flex borderColor={teamClassName === 'team1' ? 'team1' : 'team2'} borderRadius="var(--app-radius-sm)" px="0.5rem">
                {displayValue}
              </Flex>
              <Pencil
                color={teamClassName === 'team1' ? 'var(--chakra-colors-team1)' : 'var(--chakra-colors-team2)'}
                size={20}
                style={{ marginLeft: '5px' }}
                data-testid="editIcon"
              />
            </Flex>
          </div>
        )}
      </Flex>
    </>
  );
};

export default PlayerInput;
